p_ssh::options:
  ListenAddress:
    value: "0.0.0.0"
  AllowUsers:
    value:
      - root
      - maas
  PasswordAuthentication:
    value: "yes"

netname_to_interface:
  puppet: br0_default
  int: br0_1055 #tenant data between nova-compute and neutron-gateway nodes
  mgmt: br0_1056 #mysql, rabbitmq, cross openstack-services
  ceph: br0_1057 #ceph cluster and public
  ctrl: br0_1058 #public openstack services
  ext: br0_1059 #public tenant data

p_bond_to_ovs::spec_vlans:
  "1057":
    #mtu: 9000
    mtu: 1500

p_libvirt::cluster::cluster_netname: mgmt
p_libvirt::cluster::rgs:
  172.31.16.5:
    vms:
      virt1-control2:
        deployed: "FALSE"
        vcpu: 4
        mem: 8
        disks:
          - 32
  172.31.16.6:
    vms:
      virt2-db1:
        deployed: "FALSE"
        vcpu: 4
        mem: 8
        disks:
          - 32
