#p_libvirt::vms:
p_libvirt::cluster::cluster_netname: mgmt

p_ssh::options:
  ListenAddress:
    value: "%{::ipaddress_br0_default}"

netname_to_interface:
  puppet: br0_default
  int: br0_1055 #tenant data between nova-compute and neutron-gateway nodes
  mgmt: br0_1056 #mysql, rabbitmq, cross openstack-services
  ceph: br0_1057 #ceph cluster and public
  ctrl: br0_1058 #public openstack services
  ext: br0_1059 #public tenant data

p_bond_to_ovs::spec_vlans:
  "1057":
    mtu: 9000
